
services:

#  pg:
#    image: postgres
#    environment:
#      POSTGRES_DB: shop
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#
#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"

  pgadmin:
    image: postgres:16
    environment:
      POSTGRES_DB: fastapibase
      POSTGRES_USER: fastapibase
      POSTGRES_PASSWORD: fastapibase
    ports:
      - "5432:5432"